import Head from "next/head";
import Navbar from "@/components/Navbar";
import Chat from "@/components/Chat";

export default function Home() {

  return (
    <>
      <Head>
        <title>P2P Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-[#ECF2FF] min-h-screen">
         
            <>
              {/* Navbar */}
              <Navbar />
              {/* ChatRoom */}
              <Chat />
            </>
          
        </div>
      </main>
    </>
  );
}
